Repository qodo-ai/agents, pull requests merged in 2025-07, with the labels that each got.

#2 Tr/qodo merge post commit
  agents/qodo-merge-post-commit/.pre-commit-config.yaml
  agents/qodo-merge-post-commit/agent.toml
  agents/qodo-merge-post-commit/readme.md
Labels: Review effort 2/5

#5 Tr/qodo merge post commit
  agents/qodo-merge-post-commit/.pre-commit-config.yaml
  agents/qodo-merge-post-commit/agent.toml
  agents/qodo-merge-post-commit/post-commit
  agents/qodo-merge-post-commit/readme.md
Labels: Review effort 2/5

#7 Rename available_tools to tools in agent configuration files
  README.md
  agents/code-review/agent.toml
  agents/code-review/agent.yaml
  agents/code-review/qodo_merge_agent.toml
  agents/diff-test-suite/agent.toml
  agents/diff-test-suite/agent.yaml
  agents/github-issue-handler/agent.toml
  agents/github-issue-handler/agent.yaml
  agents/qodo-merge-post-commit/agent.toml
Labels: Review effort 1/5

#6 Post Commit: Support MacOS native notification, in case any high seve…
  agents/qodo-merge-post-commit/post_commit_with_notification
  agents/qodo-merge-post-commit/readme.md
Labels: Review effort 3/5

#10 feat: add an agent to remediate openssf scorecard issues
  agents/openssf-scorecard-fixer/README.md
  agents/openssf-scorecard-fixer/agent.yaml
Labels: Possible security concern, Review effort 4/5

#11 docs: add OpenSSF Scorecard Fixer agent to Community Agents section
  README.md
Labels: Review effort 1/5

#9 Added README.md documentation-writer agent
  agents/documentation-writer/README.md
  agents/documentation-writer/agent.toml
  agents/documentation-writer/agent.yaml
  agents/documentation-writer/examples/hooks/pre-push.sh
  agents/documentation-writer/examples/init-docs.sh
  agents/documentation-writer/examples/pre_commit_generation.sh
Labels: Review effort 2/5

#12 feat: add PR README Updater agent and GitHub Actions workflow
  .github/workflows/README.md
  .github/workflows/update-readme-for-merged-pr.yml
  agents/pr-readme-updater/README.md
  agents/pr-readme-updater/agent.toml
  agents/pr-readme-updater/agent.yaml
Labels: Review effort 3/5, Possible security concern

#14 fix: update mcp tools usage
  agents/openssf-scorecard-fixer/agent.yaml
Labels: Review effort 2/5, Possible security concern

#16 docs: add AWS Static Deploy agent to Community Agents section
  README.md
Labels: Review effort 1/5

#19 Add License Compliance Agent
  agents/license-compliance/README.md
  agents/license-compliance/agent.toml
  agents/license-compliance/examples/ci/Jenkinsfile
  agents/license-compliance/examples/ci/docker-example.sh
  agents/license-compliance/examples/ci/github-actions.yml
  agents/license-compliance/examples/ci/gitlab-ci.yml
  agents/license-compliance/examples/ci/pre-commit-config.yaml
  agents/license-compliance/examples/python/README.md
  agents/license-compliance/examples/python/agpl_example.py
  agents/license-compliance/examples/python/mit_example.py
  agents/license-compliance/examples/usage-examples.md
Labels: Possible security concern, Review effort 4/5
