Repository qodo-ai/agents, pull requests merged in 2025-09, with the labels that each got.

#24 docs: add Package Health Reviewer agent to Community Agents section
  README.md
Labels: Review effort 1/5

#25 feat: add test-gen agent for automated PR test coverage
  .gitignore
  agents/qodo-cover/README.md
  agents/qodo-cover/agent.toml
  agents/qodo-cover/examples/ci/github-actions.yml
Labels: Review effort 3/5

#26 Tdd junit5
  agents/tdd/junit5/README.md
  agents/tdd/junit5/agent.toml
  agents/tdd/junit5/run-example.sh
Labels: Possible security concern, Review effort 4/5

#28 feat: add Changelog / Release Notes Agent for automated changelog generation
  agents/changelog-generator/README.md
  agents/changelog-generator/agent.toml
  agents/changelog-generator/agent.yaml
  agents/changelog-generator/examples/ci-configs/github-actions.yml
  agents/changelog-generator/examples/ci-configs/gitlab-ci.yml
Labels: Review effort 2/5, Possible security concern
